### ISSUE TITLE
Missing squel package

### ISSUE THREAD

**Issue by kiro112** [anyTV/anytv-node-mysql#17]
`squel` package should be move from `devDependencies` to `dependencies`
because it is currently used at [Transaction lib](https://github.com/anyTV/anytv-node-mysql/blob/master/lib/Transaction.js#L9)

**Comment by kiro112** [comment]
#18

**Comment by FerrielMelarpis** [comment]
@kiro112 
I'm closing this issue now. 
Please reference the issue in your PR commit next time :smile:
