### ISSUE TITLE
Add support for pagination

### ISSUE THREAD

**Issue by FerrielMelarpis** [anyTV/anytv-node-mysql#8]
This will lessen the hassle of creating helpers in projects for handling pagination.
We should be able to do this:
```js
mysql.use(db)
    // page, per_page should have default
    // can be called as .paginate(query, callback)
    .paginate(query, page, per_page, callback)
    .end();

function callback (err, result, args, last_query) {
    // if query was as `squel` instance, `last_query` would be an `squel` instance. 
    // Otherwise, it would be a string.
    ...
    last_query.left_join('table', 'tb', 'tb.a = orig_table.a');
    ...
    mysql.use(db)
        // result would be an object with pagination properties
        // { page: 1, per_page: 15, total: 1000 }
        .squel(last_query, return_result, result)
        .end();
}

function return_result (err, result, args) {
    if (err) {
        return res.error(err);
    }
    
    res.data(args).items(result).send();
}
```

**Comment by ravenjohn** [comment]
`squel` has `.limit()` and `.offset()`, how is this better than applying pagination in the squel query?

**Comment by FerrielMelarpis** [comment]
When doing pagination, you also need to get the total. Normally, we are going to run a query for getting the `count(*)` then run the query that actually gets the fields. I was thinking if it is here, we could just pass the query, page and per_page. Then, behind the scenes, we will clone the query, add `SQL_CALC_FOUND_ROWS` in `squel.select()`. Run a **transaction** (taking into consideration that `anytv-node-mysql` supports multiple pools) with that query including a new query `SELECT FOUND_ROWS() AS total;` then create a result object containing `page`, `per_page`, `total`, and `result`. This way the result object would already contain the necessary info for a simple pagination however, if we are planning to support a way to optimize pagination in cases like `LEFT JOIN` without filtering which does not affect the total count of records, we can chain the result to another `mysql.squel()` then pass result as `args`.
My example above does that.

**Comment by pandafox** [comment]
I think we should avoid usage of a transaction if possible, especially if we're just doing read.  Please keep that in mind.

**Comment by FerrielMelarpis** [comment]
@pandafox We can avoid unnecessary usage of transaction if there is only one pool being used. If there are multiple pools, we can concatenate the two queries with a semi-colon then send it in one connection so `FOUND_ROWS()` would return the correct value.

**Comment by pandafox** [comment]
This is a bit scary

"Many of the comments to the post seem to say that SQL_CALC_FOUND_ROWS is almost always slower - sometimes up to 10x slower - than running two queries."

http://stackoverflow.com/questions/186588/which-is-fastest-select-sql-calc-found-rows-from-table-or-select-count

**Comment by FerrielMelarpis** [comment]
hmmm that is a pretty old topic however, in mysql's documentation
https://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_found-rows
> If you are using `SELECT SQL_CALC_FOUND_ROWS`, MySQL must calculate how many rows are in the full result set. However, this is faster than running the query again without LIMIT, because the result set need not be sent to the client.

A couple of things I've found rather curious from the post is the citation of this benchmark 
https://www.percona.com/blog/2007/08/28/to-sql_calc_found_rows-or-not-to-sql_calc_found_rows/
- The schema used was simple.
- The query was actually a bug that is still existing in mysql 5.7 greatly affecting in innodb engine
  https://bugs.mysql.com/bug.php?id=18454

If we're going to do this I think doing `COUNT(1)` is safer since `SQL_CALC_FOUND_ROWS` is not yet stable. In addition, we should apply proper indexing on tables that will use pagination since `COUNT(1)` also relies on INDEXES. `SQL_CALC_FOUND_ROWS` is found to be buggy when `ORDER BY` clauses are included which we almost always do. Also, in my suggestion, we have an option of trimming the query for unnecessary joins as sampled above in the issue description. So, we might be able to optimize the use of `COUNT` by doing that.

**Comment by pandafox** [comment]
1. I agree we can do two queries for count(1)
2. I don't think we can safely trim/remove unnecessary joins in the library, if it can be done, SQL would have done it already.

**Comment by FerrielMelarpis** [comment]
Yes it is not safe but can be done manually. It will be made available by returning the last_query but it is still just an option to do that.

**Comment by FerrielMelarpis** [comment]
This thread might help us on some optimizations http://stackoverflow.com/questions/2710621/count-vs-count1-vs-countpk-which-is-better

**Comment by FerrielMelarpis** [comment]
Hmmm, I think we can use squel custom queries
for building pagination query

> https://hiddentao.com/squel/index.html#custom_queries

anytv-node-mysql should only be concerned of sending the query to the db and returning the value received from db.
